# Generated by Django 3.2.12 on 2023-06-08 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Douban',
            fields=[
                ('update_time', models.DateTimeField(auto_created=True, auto_now_add=True, help_text='更新时间')),
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('img', models.CharField(help_text='图片地址', max_length=1024)),
                ('href', models.CharField(help_text='书籍地址', max_length=1024)),
                ('title', models.CharField(help_text='标题', max_length=128)),
                ('read', models.BooleanField(help_text='可试读')),
                ('make', models.CharField(help_text='制造说明', max_length=1024)),
                ('score', models.DecimalField(decimal_places=1, help_text='评分', max_digits=2)),
                ('appraise', models.IntegerField(help_text='好评度')),
                ('intro', models.CharField(help_text='简介', max_length=1024)),
            ],
        ),
    ]
